name: Run Fuzz Testing

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.py'

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r KubeSec-master/requirements.txt

    - name: Run fuzz tests
      run: python fuzz.py
